<?php

namespace abd\BlogBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends EntityRepository
{
    public function getFrontPost($locale)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT p, t FROM abdBlogBundle:Post p '.
            'JOIN p.translations t '.
            'WHERE t.locale = :locale ' .
            'ORDER BY p.creado '
        )->setParameter('locale', $locale);

        $query->setFirstResult(0)
            ->setMaxResults(8);

        return $query->getResult();

        #$paginator = new Paginator($query, $fetchJoinCollection = true);

        #return $paginator;
    }

    public function getImageGallery()
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT p.imagen FROM abdBlogBundle:Post p '.
            'ORDER BY p.creado '
        )->setMaxResults(4);

        return $query->getResult();
    }
}