<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlquilerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlquilerRepository extends EntityRepository {

    public function getOferta($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT alq,alqart,art, o FROM AppBundle:Alquiler alq ' .
            'JOIN alq.alquilerArticulos alqart '.
            'JOIN alqart.articulo art '.
            'JOIN alq.oferta o ' .
            'WHERE alq.id = :id '
        )->setParameter('id', $id);
        $result = $query->getSingleResult();
        return $result;
    }

    public function getArticulos($id) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT alq,alqart,art FROM AppBundle:Alquiler alq ' .
                        'JOIN alq.alquilerArticulos alqart '.
                        'JOIN alqart.articulo art '.
                        'WHERE alq.id = :id '
                )->setParameter('id', $id);
        $result = $query->getSingleResult();
        return $result;
    }

    public function getByEmailCode($correo,$codigo) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT alq FROM AppBundle:Alquiler alq ' .
            'JOIN alq.cliente cl '.
            'WHERE alq.codigo = :codigo '.
            'AND cl.correo = :correo '
        )->setParameter('codigo', $codigo)
        ->setParameter('correo', $correo);
        $result = $query->getOneOrNullResult();
        return $result;
    }
    
}
