<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * AlquilerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeguroRepository extends EntityRepository {

    public function getIdIn($ids) {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
                        'SELECT s FROM AppBundle:Seguro s ' .
                        'WHERE s.id in (:ids) '
                )->setParameter('ids', $ids);
        $result = $query->getResult();
        return $result;
    }
    
}
