<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * OfertaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TextoRepository extends EntityRepository
{
    public function getTextoByTipo($tipo,$locale)
    {
        $em = $this->getEntityManager();
        $query = $em->createQuery(
            'SELECT t FROM AppBundle:Texto t '.
            'JOIN t.translations tr '.
            'JOIN t.tipo tp '.
            'WHERE tp.id = :tipo ' .
            'AND tr.locale = :locale '
        )->setParameter('locale', $locale)
        ->setParameter('tipo', $tipo);
        return $query;
    }
}